spring.application.name=AstroDesk-Backend

spring.datasource.url=jdbc:postgresql://localhost:5432/appdb
spring.datasource.username=appuser
spring.datasource.password=apppassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.flyway.enabled=true

ldap.url=ldap://localhost:389
ldap.base=dc=astrodesk
ldap.dn=cn=admin,dc=astrodesk
ldap.pwd=adminpassword
