services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    command: ["--copy-service"]
    environment:
      LDAP_ORGANISATION: "Astrodesk"
      LDAP_DOMAIN: "astrodesk"
      LDAP_ADMIN_PASSWORD: "adminpassword"
      LDAP_TLS: "false"
    ports:
      - "389:389"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./user.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/user.ldif
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - ldap
    ports:
      - "8081:80"
    restart: unless-stopped

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_DB: "appdb"
      POSTGRES_USER: "appuser"
      POSTGRES_PASSWORD: "apppassword"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./backup_restore.sh:/backup_restore.sh
      - ./backups:/backups
    restart: unless-stopped

  backup:
    image: alpine:latest
    container_name: backup
    depends_on:
      - postgres
    volumes:
      - ./backup.sh:/backup.sh
      - ./backups:/backups
    environment:
      PGPASSWORD: "apppassword"
      PGHOST: "postgres"
      PGUSER: "appuser"
      PGDATABASE: "appdb"
      TZ: Europe/Warsaw
    entrypoint: >
      sh -c "
      chmod +x /backup.sh &&
      apk add postgresql-client tzdata &&
      cp /usr/share/zoneinfo/Europe/Warsaw /etc/localtime &&
      echo 'Europe/Warsaw' > /etc/timezone && 
      echo '* * * * * /backup.sh' > /etc/crontabs/root &&
      echo 'DONE' &&
      exec crond -f -l 2
      "


volumes:
  ldap_data:
  ldap_config:
  pg_data:

